{
 "title": "Glitchtip-Jira",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Received Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Received Alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(gjb_received_alerts_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Received Alerts/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gjb_received_alerts_total[$__interval]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Received Alerts per Jira Project",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gjb_received_alerts_total[$__range])) by (jira_project_key)",
     "legendFormat": "{{jira_project_key}}"
    }
   ]
  },
  { "title": "Jira tickets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Tickets created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "sum(gjb_tickets_created_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tickets Created/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(gjb_tickets_created_total[$__interval]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Tickets create per Jira Project",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(gjb_tickets_created_total[$__range])) by (jira_project_key)",
     "legendFormat": "{{jira_project_key}}"
    }
   ]
  },
  { "title": "Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Limit reached per Jira Project",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(gjb_limit_reached_total[$__range])) by (jira_project_key)",
     "legendFormat": "{{jira_project_key}}"
    }
   ]
  },
  { "title": "Pod Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Web Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"glitchtip-jira-bridge-prod\", container=\"web\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"glitchtip-jira-bridge-prod\", container=\"web\", resource=\"memory\"})",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"glitchtip-jira-bridge-prod\", container=\"web\", resource=\"memory\"})",
     "legendFormat": "Memory Request"
    }
   ]
  },
  {
   "title": "Web Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"glitchtip-jira-bridge-prod\", pod=~\".*-web.+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"glitchtip-jira-bridge-prod\", container=\"worker\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"glitchtip-jira-bridge-prod\", container=\"worker\", resource=\"memory\"})",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"glitchtip-jira-bridge-prod\", container=\"worker\", resource=\"memory\"})",
     "legendFormat": "Memory Request"
    }
   ]
  },
  {
   "title": "Worker Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{namespace=\"glitchtip-jira-bridge-prod\", pod=~\".*-worker.+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}